### ISSUE TITLE
configure: error: The Fortran compiler gfortran will not compile files that call

### ISSUE THREAD

**Issue by dembart** [jcklasseter/SISSO_docker#1]
Hi, I have an error while compiling the code. Is there a workaround?

#0 16.09 checking whether gfortran allows mismatched arguments... configure: error: The Fortran compiler gfortran will not compile files that call
#0 16.11 the same routine with arguments of different types.
#0 16.11 no
------
Dockerfile:17
--------------------
  15 |     RUN mkdir mpich-install
  16 |     RUN mkdir mpich-build
  17 | >>> RUN cd mpich-build && ../mpich-3.3.2/configure -prefix=/root/mpich-install 
  18 |     RUN cd mpich-build && make && make install
  19 |     ENV PATH="/root/mpich-install/bin:${PATH}"

**Comment by jcklasseter** [comment]
Possibly newer software causing issues? I think you could pin the ubuntu or gfortran versions? I'll try to test it out soon

**Comment by dembart** [comment]
I am compiling on OSX Ventura
GNU Fortran (Homebrew GCC 13.1.0) 13.1.0

**Comment by jcklasseter** [comment]
That shouldn’t matter with Docker. What ubuntu version are you pulling
through docker?

If you’re not using docker, yeah it may never work. I dockerized the sisso
code due to how annoying it is to run bare metal on os x. I do not maintain
sisso, you’d have to ask them on the actual sisso repo for help with bare
metal install

**Comment by dembart** [comment]
Sorry for the poor delivery of the problem.

I used Docker and followed the instructions. Dockerfile was kept as is:
FROM ubuntu:latest

**Comment by jcklasseter** [comment]
I replicated your issue, and moved to Intel oneAPI to fix it
